chore: testing git clone

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -12,33 +12,36 @@ if [ "$ASDF_INSTALL_TYPE" != "version" ]; then
 	fail "asdf-$TOOL_NAME supports release installs only. See asdf list all $TOOL_NAME for a list of supported versions."
 fi
 
-(
-	# TODO(jthegedus): "asdf install v latest" does not work
-	# error output
-	#
-	# * Downloading v@0.3
-	# warning: Could not find remote branch 0.3? to clone.
-	# fatal: Remote branch 0.3? not found in upstream origin
-	# asdf-v: Could not download https://github.com/vlang/v
-	# .sdf-v: An error ocurred while installing v 0.3
-	printf "* Downloading %s@%s\\n" "$TOOL_NAME" "$ASDF_INSTALL_VERSION"
-	mkdir -p "$ASDF_INSTALL_PATH"
-	git clone -c advice.detachedHead=false --depth 1 --branch "$ASDF_INSTALL_VERSION" "$GH_REPO" "$ASDF_INSTALL_PATH" || fail "Could not download $GH_REPO"
-	printf "* Downloaded to %s\\n" "$ASDF_INSTALL_PATH"
+mkdir -p "$ASDF_INSTALL_PATH"
+git clone -c advice.detachedHead=false --depth 1 --branch "$ASDF_INSTALL_VERSION" "$GH_REPO" "$ASDF_INSTALL_PATH" || fail "Could not download $GH_REPO"
 
-	printf "* Building %s@%s from source\\n" "$TOOL_NAME" "$ASDF_INSTALL_VERSION"
-	make --quiet -C "$ASDF_INSTALL_PATH" || fail "Could not compile $TOOL_NAME@$ASDF_INSTALL_VERSION"
+# (
+# 	# TODO(jthegedus): "asdf install v latest" does not work
+# 	# error output
+# 	#
+# 	# * Downloading v@0.3
+# 	# warning: Could not find remote branch 0.3? to clone.
+# 	# fatal: Remote branch 0.3? not found in upstream origin
+# 	# asdf-v: Could not download https://github.com/vlang/v
+# 	# .sdf-v: An error ocurred while installing v 0.3
+# 	printf "* Downloading %s@%s\\n" "$TOOL_NAME" "$ASDF_INSTALL_VERSION"
+# 	mkdir -p "$ASDF_INSTALL_PATH"
+# 	git clone -c advice.detachedHead=false --depth 1 --branch "$ASDF_INSTALL_VERSION" "$GH_REPO" "$ASDF_INSTALL_PATH" || fail "Could not download $GH_REPO"
+# 	printf "* Downloaded to %s\\n" "$ASDF_INSTALL_PATH"
 
-	printf "* Symlinking binary to %s/bin/%s dir\\n" "$ASDF_INSTALL_PATH" "$TOOL_NAME"
-	mkdir -p "$ASDF_INSTALL_PATH/bin"
-	ln -s "$ASDF_INSTALL_PATH/$TOOL_NAME" "$ASDF_INSTALL_PATH/bin/$TOOL_NAME"
-	# mv "$ASDF_INSTALL_PATH/$TOOL_NAME" "$ASDF_INSTALL_PATH/bin/$TOOL_NAME"
+# 	printf "* Building %s@%s from source\\n" "$TOOL_NAME" "$ASDF_INSTALL_VERSION"
+# 	make --quiet -C "$ASDF_INSTALL_PATH" || fail "Could not compile $TOOL_NAME@$ASDF_INSTALL_VERSION"
 
-	printf "* Testing if %s@%s is executable\\n" "$TOOL_NAME" "$ASDF_INSTALL_VERSION"
-	tool_cmd="$(printf "%s\\n" "$TOOL_TEST" | cut -d' ' -f1)"
-	test -x "$ASDF_INSTALL_PATH/bin/$tool_cmd" || fail "Expected $ASDF_INSTALL_PATH/bin/$tool_cmd to be executable."
-	printf "* Success! %s@%s is ready for use.\\n" "$TOOL_NAME" "$ASDF_INSTALL_VERSION"
-) || (
-	rm -rf "$ASDF_INSTALL_PATH"
-	fail "An error ocurred while installing $TOOL_NAME@$ASDF_INSTALL_VERSION."
-)
+# 	printf "* Symlinking binary to %s/bin/%s dir\\n" "$ASDF_INSTALL_PATH" "$TOOL_NAME"
+# 	mkdir -p "$ASDF_INSTALL_PATH/bin"
+# 	ln -s "$ASDF_INSTALL_PATH/$TOOL_NAME" "$ASDF_INSTALL_PATH/bin/$TOOL_NAME"
+# 	# mv "$ASDF_INSTALL_PATH/$TOOL_NAME" "$ASDF_INSTALL_PATH/bin/$TOOL_NAME"
+
+# 	printf "* Testing if %s@%s is executable\\n" "$TOOL_NAME" "$ASDF_INSTALL_VERSION"
+# 	tool_cmd="$(printf "%s\\n" "$TOOL_TEST" | cut -d' ' -f1)"
+# 	test -x "$ASDF_INSTALL_PATH/bin/$tool_cmd" || fail "Expected $ASDF_INSTALL_PATH/bin/$tool_cmd to be executable."
+# 	printf "* Success! %s@%s is ready for use.\\n" "$TOOL_NAME" "$ASDF_INSTALL_VERSION"
+# ) || (
+# 	rm -rf "$ASDF_INSTALL_PATH"
+# 	fail "An error ocurred while installing $TOOL_NAME@$ASDF_INSTALL_VERSION"
+# )
