chore: revert quiet flag on clone

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -13,9 +13,17 @@ if [ "$ASDF_INSTALL_TYPE" != "version" ]; then
 fi
 
 (
+	# TODO(jthegedus): "asdf install v latest" does not work
+	# error output
+	#
+	# * Downloading v@0.3
+	# warning: Could not find remote branch 0.3? to clone.
+	# fatal: Remote branch 0.3? not found in upstream origin
+	# asdf-v: Could not download https://github.com/vlang/v
+	# .sdf-v: An error ocurred while installing v 0.3
 	printf "* Downloading %s@%s\\n" "$TOOL_NAME" "$ASDF_INSTALL_VERSION"
 	mkdir -p "$ASDF_INSTALL_PATH"
-	git clone --quiet -c advice.detachedHead=false --depth 1 --branch "$ASDF_INSTALL_VERSION" "$GH_REPO" "$ASDF_INSTALL_PATH" || fail "Could not download $GH_REPO"
+	git clone -c advice.detachedHead=false --depth 1 --branch "$ASDF_INSTALL_VERSION" "$GH_REPO" "$ASDF_INSTALL_PATH" || fail "Could not download $GH_REPO"
 	printf "* Downloaded to %s\\n" "$ASDF_INSTALL_PATH"
 
 	printf "* Building %s@%s from source\\n" "$TOOL_NAME" "$ASDF_INSTALL_VERSION"
@@ -32,5 +40,5 @@ fi
 	printf "* Success! %s@%s is ready for use.\\n" "$TOOL_NAME" "$ASDF_INSTALL_VERSION"
 ) || (
 	rm -rf "$ASDF_INSTALL_PATH"
-	fail "An error ocurred while installing $TOOL_NAME $ASDF_INSTALL_VERSION."
+	fail "An error ocurred while installing $TOOL_NAME@$ASDF_INSTALL_VERSION."
 )
