feat: handle commit ref installs

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -40,7 +40,16 @@ fi
 (
 	printf "* Downloading %s@%s\\n" "$TOOL_NAME" "$ASDF_INSTALL_VERSION"
 	mkdir -p "$ASDF_INSTALL_PATH"
-	git clone --quiet -c advice.detachedHead=false --depth 1 --branch "$ASDF_INSTALL_VERSION" "$GH_REPO" "$ASDF_INSTALL_PATH" || fail "Could not download $GH_REPO"
+	if [ "$ASDF_INSTALL_TYPE" == "version" ]; then
+		# clone branch/tag
+		printf "%s\\n" "TAG"
+		git clone --quiet -c advice.detachedHead=false --depth 1 --branch "$ASDF_INSTALL_VERSION" "$GH_REPO" "$ASDF_INSTALL_PATH" || fail "Could not download $GH_REPO @ $ASDF_INSTALL_VERSION"
+	else
+		# clone commit/ref/sha
+		printf "%s\\n" "COMMIT"
+		git clone --depth 1 "$GH_REPO" "$ASDF_INSTALL_PATH" || fail "Could not download $GH_REPO @ $ASDF_INSTALL_VERSION"
+		git checkout --quiet -c advice.detachedHead=false "$ASDF_INSTALL_VERSION" || fail "Could not reach $ASDF_INSTALL_VERSION in Git tree"
+	fi
 	printf "* Downloaded to %s\\n" "$ASDF_INSTALL_PATH"
 
 	printf "* Building %s@%s from source\\n" "$TOOL_NAME" "$ASDF_INSTALL_VERSION"
